apiVersion: apps/v1
kind: Deployment
metadata:
  name: amine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amine
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: amine
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: my-job
        image: 20.225.57.67:8083/my-job:$IMAGE_NAME
        imagePullPolicy: Always
      imagePullSecrets:
      - name: nexus-docker  
        ports:
            - name: http
              containerPort: 8080
              protocol: TCP
        resources:
            requests:
              cpu: 400m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: amine
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: amine
---
apiVersion: v1
kind: Service
metadata:
  name: amine-cluster-ip
spec:
  selector:
    app: amine
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
